spring:
  application:
    name: gatway-service
  main:
    web-application-type: reactive
    
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    
   

server:
  port: 9895
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
             
debug: true
      
      
            
